### ISSUE TITLE
Additional babel presets are prepended

### ISSUE THREAD

**Issue by Zycon42** [sharegate/craco#100]
When you specify babel presets or plugins in craco configuration
```js
module.exports = {
  babel: {
    presets: [/* your babel presets */]
  }
}
```

they are added BEFORE babel-preset-react-app. I use '@emotion/babel-preset-css-prop' which must to be added AFTER react-app preset otherwise it won't work.

When you use
```js
module.exports = {
  babel: {
    loaderOptions: { presets: [/* your babel presets */] }
  }
}
```

the presets are appended like I need but won't be picked up by jest transformer.

IMHO there should be a way how to specify where you want babel-preset-react-app to be put. Or appending could be default but I don't know if any presets in the wild need to be put before babel-preset-react-app.

**Comment by patricklafrance** [comment]
Hi @Zycon42 

I will certainly look into it, there seems to be something wrong with the way the babel presets are currently handled by CRACO.

In the meantime, you could fix your problem by using this plugin: https://github.com/jackwilsdon/craco-use-babelrc

And define a custom .babelrc file at the root of your project with something like this:

```javascript
{
    "presets: ["babel-preset-react-app", "@emotion/babel-preset-css-prop"]
}
```

Hope this help!

Patrick
