### ISSUE TITLE
How would I go about setting up TypeScript => ES6 => Babel => ES5?

### ISSUE THREAD

**Issue by ndbroadbent** [sharegate/craco#12]
This came up because when I used `"target": "es5"`, I started getting type errors when I tried to use `Array.from` ("Property 'from' does not exist on type 'ArrayConstructor'").

I'm using TypeScript, so I think I'd like to set `"target": "es6"` so that I can use modern JS features and new methods, and have tree shaking, etc. But I also need backwards compatibility for older browsers, so I think I need Babel for ES6 => ES5, and will include `babel-polyfill`.

I'm new to TypeScript so I'm not sure how all of this fits together (but I have experience with Flow, webpack, and babel.) Apparently another option is to just include `core-js`, and then set this in my `tsconfig.json`:

```
 target: "es5"
 lib: ["es2018"]
```

Then TypeScript will use the types from the latest ES version, and it just assumes that a polyfill has been loaded in the browser. But I think if TypeScript is emitting ES5 to Webpack then I lose tree shaking. (But not sure)

I would like to please request a new recipe for the TS => ES6 => Babel => ES5 configuration, including a polyfill. I'm not sure how to configure the loaders properly for webpack.

**Comment by ndbroadbent** [comment]
Actually never mind! I just read through the `react-scripts` webpack config and `babel-preset-react-app`, and I discovered that are already doing everything with 100% Babel. (They aren't using `ts-loader` or `awesome-typescript-loader`). Apart from the typechecking - that's run in a different process, but isn't part of the actual webpack build.

So I think everything should just be working out of the box, and all I need to do is set `"target": "es6"` in my `tsconfig.json`.

**Comment by arietrouw** [comment]
how do I use craco to prevent babel from processing certain imported assets?
