### ISSUE TITLE
Usage with yarn workspaces

### ISSUE THREAD

**Issue by teevik** [sharegate/craco#2]
The error:
```
$ yarn run dev
yarn run v1.10.1

$ craco start
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\WebDev\coding-tracker\packages\client\node_modules\react-scripts/config/paths.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at resolveConfigFilePath (C:\WebDev\coding-tracker\node_modules\@craco\craco\lib\cra.js:24:20)
    at Object.<anonymous> (C:\WebDev\coding-tracker\node_modules\@craco\craco\lib\cra.js:38:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---

I'm using yarn workspaces for a monorepo, so all the node_modules is shared in a single folder. My app has a structrue like this:
```
coding-tracker/
├── node_modules/
└── packages/
    ├── api/
    ├── shared/
    └── client/
```

Now the problem is that craco looks for the react-scripts files in `coding-tracker/packages/client/node_modules` instead of `coding-tracker/node_modules`

I'm pretty sure that's because `process.cwd()` would be `coding-tracker/packages/client`: https://github.com/sharegate/craco/blob/master/packages/craco/lib/paths.js#L4

I made a quick workaround in my case by doing this:

```diff
function getReactScriptsFolderPath() {
-   let filepath = "";
+   let filepath = "react-scripts";

-   if (args.reactScripts.isOverrided) {
-       filepath = path.resolve(`${projectRoot}/${args.reactScripts.value}/`);
-   } else {
-       filepath = path.resolve(`${nodeModulesPath}/react-scripts/`);
-   }

    log("Found react scripts folder at: ", filepath);

    return filepath;
}

**Comment by patricklafrance** [comment]
Thank you for your bug report and your solution, I will look into this before the end of the week!

**Comment by patricklafrance** [comment]
@teevik I will add support for workspace to make it easier to configure but in the meantime what you can do is:

`craco start --react-scripts ../../../node_modules/react-scripts`

**Comment by axelchalon** [comment]
Hi! The `test` command doesn't seem to take the `--react-scripts` value into account:

`craco test --react-scripts ../../node_modules/react-scripts`

```
 FAIL  src/stores/sendStore.spec.js
  ● Test suite failed to run

    Cannot find module '/home/nicolas/www/fether/packages/fether-react/node_modules/react-scripts/config/paths.js'
```

`craco {build,start} --react-scripts ../../node_modules/react-scripts` both work fine though!

**Comment by iamawebgeek** [comment]
@axelchalon +1. passing `--workspace` flag did not help as well

**Comment by patricklafrance** [comment]
I will look into this as soon as possible. Thank you.

**Comment by patricklafrance** [comment]
@iamawebgeek @axelchalon could you provide a simple repository that reproduce the case?

It works fine with my sandbox project with either the --workspace flag or by providing a custom --react-scripts path

```
"test": "craco test --verbose --workspace",
"test-react-scripts": "craco test --verbose --react-scripts ../../node_modules/react-scripts-custom"
```

Thank you

**Comment by axelchalon** [comment]
yes, https://github.com/axelchalon/craco-issue

Notice how `yarn start` works but `yarn test` doesn't.

Some observations: tests work if there is only one test file, and tests work if I remove `babel: {...}` from the export of `craco.config.js`

**Comment by patricklafrance** [comment]
Thank you @axelchalon 

Oh that explains why, my sandbox project contains a single file.

**Comment by patricklafrance** [comment]
It took a while but I finally found some time to work on this!

It was not an easy one.

I published an alpha version, if anyone can try it: https://www.npmjs.com/package/@craco/craco/v/4.0.0

The problem was that the `--workspace`, `--scripts-version` and `--react-scripts` options are provided by the CLI and the custom `babel-jest` transformer provided by `craco` doesn't have access to those options since it's call directly by Jest in another process.

The solution is to define those options in the `craco.config.js` file.

You can have a look here for the config: https://github.com/sharegate/craco/blob/add-paths-to-config-file/packages/craco/README.md#configuration-overview

Of course there is some drawback...

-  `--workspace`, `--scripts-version` and `--react-scripts` cannot be specified by the CLI anymore.
- Custom location for the config file (`--config`) cannot be specified if you need to use `craco` support for `babel-jest`

@axelchalon @iamawebgeek

**Comment by axelchalon** [comment]
Can confirm `craco {test,build,start}` all work fine with craco v4.0.0 and specifying `reactScriptsPath` in craco.config.js :+1: thank you!
