### ISSUE TITLE
Is there a list of plugins?

### ISSUE THREAD

**Issue by HasanAyan** [sharegate/craco#32]
Hi, thanks for making craco. I adapted react-app-rewire-hot-loader to a craco plugin and thought if you keep a list of plugins this could be useful for others, too.

Here is my plugin: https://github.com/HasanAyan/craco-plugin-react-hot-reload

**Comment by patricklafrance** [comment]
Hi @HasanAyan 

Yes it's in the README at the root of repo https://github.com/sharegate/craco/blob/master/README.md

Can you send a PR to add your plugin? Otherwise i'll do it as soon as I can :)

Thanks for the plugin!

**Comment by patricklafrance** [comment]
Done!
