### ISSUE TITLE
Line Endings causing ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by cammanderson** [sharegate/craco#33]
Hi Guys, 

Thanks for writing the package!

We are trying to get this running in our teams, on various environments, but our Linux and Mac users have problems with the line endings.

```sh
$ craco build
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
```

Is it possible to have the \r removed?

Thanks!
Cam

**Comment by abenhamdine** [comment]
Same here, seemingly since update 2.4.0

**Comment by patricklafrance** [comment]
Sorry about that, I will update the line endings to LF instead of CRLF.

**Comment by patricklafrance** [comment]
It should be fix with 3.0.0 alpha

@cammanderson @abenhamdine can you test it please?

**Comment by yurtaev** [comment]
@patricklafrance It's fixed in 3.0 👍

**Comment by patricklafrance** [comment]
@yurtaev thank you!

**Comment by abenhamdine** [comment]
Works fine with 3.0.0, thx @patricklafrance !
