### ISSUE TITLE
Watching tests not working with IntelliJ's Jest Run Configuration

### ISSUE THREAD

**Issue by Lukas-Kullmann** [sharegate/craco#39]
We recently switched from react-scripts v1 to v2. And with that, we now also use craco to rewire some configurations. (Thanks btw. for the awesome package. We used react-app-rewired and the configuration for craco is much nicer and easier to understand!)

Everything works fine so far, except the watch mode of tests in IntelliJ's Jest Run Configuration does not work properly.
The first run passes without any problem, but as soon as a file changes and a new test run is therefor triggered, the `src/setupTests.ts` file is not loaded again. Meaning that enzyme throws an error since no enzyme adapter is configured any more. (Other packages also throw errors since they are not initialized properly)

When I run the test in the regular terminal with the same configuration that I apply in IntelliJ (e.g. `yarn run craco test --env=jsdom --watch`), watching works normally and does not throw any errors.

Does anyone know how to fix this? I really do not want to loose the IntelliJ test result reporting since it makes working with tests so much easier.

I'm using react-script@2.1.1 and craco@3.1.1 if that makes any difference.

**Comment by patricklafrance** [comment]
Hi @Lukas-Kullmann 

I am not an IntelliJ user so it's hard for me to support it.

react-app-rewired have a fix for IntelliJ support: https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/bin/jest.js

If you have time, you could try to add it to craco and send a PR! :)

Thank you

**Comment by patricklafrance** [comment]
Hi @Lukas-Kullmann 

I pushed a fix for IntelliJ in the 3.2.0 release.

Can you try it?

Thank you

**Comment by Lukas-Kullmann** [comment]
Does not work, unfortunately. :/

**Comment by patricklafrance** [comment]
I will close this issue, @Lukas-Kullmann feel free to open it again once you have news from IntelliJ

**Comment by Lukas-Kullmann** [comment]
Just to give you an update on this, it works in the new 2018.3.2 version of IntelliJ, which was released Dec. 19th 2018. :)
