### ISSUE TITLE
Functional example of decorators?

### ISSUE THREAD

**Issue by Strnadj** [sharegate/craco#40]
We are trying to use http://inversify.io/, it uses attribute decorators to inject:

```
     constructor(@inject(TYPES.Repository) repository) {

     }
```

but if I try to use `mobX` configuration (add decorator support), I am still getting:

```
Module parse failed: Unexpected character '@' (41:21)
You may need an appropriate loader to handle this file type.
| /*#__PURE__*/
| function () {
>   function TestUsage(@inject(TYPES.Test)
|   test) {
|     _classCallCheck(this, TestUsage);
```

I think this issue is caused by the configuration of webpack in CRA, they are not using ts-loader, but I am not sure.

**Comment by patricklafrance** [comment]
Hi @Strnadj 

Have you tried this recipe? https://github.com/sharegate/craco/tree/master/recipes/use-mobx

**Comment by Strnadj** [comment]
Yes, we have tried that, but it fails with the error message above.

**Comment by patricklafrance** [comment]
There is a few options for the babel decorator plugin: https://babeljs.io/docs/en/next/babel-plugin-proposal-decorators.html#legacy

Have tryed without the `legacy` option?

```
module.exports = {
    babel: {
        plugins: [
            ["@babel/plugin-proposal-decorators"]
        ]
    }
};
```

**Comment by Strnadj** [comment]
Ok, if I delete that:

```./node_modules/react-dev-utils/webpackHotDevClient.js
Error: [BABEL] /Users/strnadj/Projects/test/node_modules/react-dev-utils/webpackHotDevClient.js: The decorators plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you want to use the legacy decorators semantics, you can set the 'legacy: true' option. (While processing: "/Users/strnadj/Projects/test/node_modules/@babel/plugin-proposal-decorators/lib/index.js")
    at Array.reduce (<anonymous>)
```

so I have change that to:
```
module.exports = {
    babel: {
        plugins: [
          ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true } ],
        ]
    }
};
```

and error:

```
Failed to compile.

./src/index.tsx
Error: Cannot use the decorators and decorators-legacy plugin together
```

**Comment by patricklafrance** [comment]
I tryed it on my side and it works fine.

I guess you have something else in your setup that add the `decorators-legacy` plugin?

**Comment by Strnadj** [comment]
https://github.com/Strnadj/not_working_cra there is repository, what cames in my mind... it seems to "@babel/plugin-proposal-decorators" is not ready yet for @babel 7.1..

```warning " > @babel/plugin-proposal-decorators@7.1.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
```
not sure if it is a problem, but I was not able to find react-scripts version with @babel 7.0 in dependencies.

**Comment by patricklafrance** [comment]
Maybe it's the problem, if it's the case you should open an issue in the `@babel/plugin-proposal-decorators` repository.

For this issue, it doesn't seem to be a problem with `craco`.

If you find the right `webpack` recipe for `inversify` i'll be glad to help you to make it work with `CRA` + `craco`.

I will leave the issue open for a few days in case someone have a solution for you.

**Comment by duyucongc** [comment]
Hi @patricklafrance 
I use config

```
module.exports = {
    babel: {
        plugins: [
            ["@babel/plugin-proposal-decorators", { legacy: true }]
        ]
    }
};
```
and it work in  **craco start** and **craco build**
but when I run **craco test**
It failed with error
`Support for the experimental syntax 'decorators-legacy' isn't currently enabled
`
What should I change config to fit CRX test ?

**Comment by patricklafrance** [comment]
@duyucongc https://www.npmjs.com/package/@craco/craco/v/3.2.2 should fix your problem .

**Comment by patricklafrance** [comment]
I will close this issue since there isn't any new comments for 7 days

**Comment by duyucongc** [comment]
Thank you, this did solve my problem. I originally planned to use mobx directly without using the decorator.

**Comment by zhang14725804** [comment]
@patricklafrance thank you it did work for me
