### ISSUE TITLE
Override webpack optimization

### ISSUE THREAD

**Issue by carlosfunk** [sharegate/craco#44]
Hi,
I need some help trying to override the settings in TerserPlugin to disable mangling.  Is this supported currently?  I've tried setting up something like this but it doesn't seem to take effect...  Not 100% sure I'm doing it correctly.

```
webpack: {
    optimization: {
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            mangle: false
...
```

The configuration I'm trying to modify is here https://github.com/facebook/create-react-app/blob/49e258b4a6d04fb7e3542d7a060c6dcad4093564/packages/react-scripts/config/webpack.config.js#L182

**Comment by patricklafrance** [comment]
Hi @carlosfunk 

Yes it is supported but you have to use

```
webpack: {
    configure: {
        optimization: { .... }
    }
}
```

or

```

**Comment by patricklafrance** [comment]
I will close this issue since there isn't any new comments for 7 days.

**Comment by tmock12** [comment]
@patricklafrance I have the same need, does the merge work? 

Wouldn't the merge just concat a completely new object?  something like : 

```
{ optimization:
  {minimizer: [ TerserPlugin, TerserPlugin ] }
}
```

**Comment by patricklafrance** [comment]
@tmock12 Craco doesn't merge the webpack section. To merge you have to use 

```
webpack: {
    configure: {
        optimization: { .... }
    }
}
```

**Comment by tmock12** [comment]
@patricklafrance 

I think I'm missing something. But when you do use configure, like you have posted:

```
webpack: {
    configure: {
        optimization: { minimizer: [new TerserPlugin()] }
    }
}
```

wouldn't the merged config have two of those `TerserPlugin` objects?

```
 {
    optimization: { minimizer: [TerserPlugin, TerserPlugin] }
  }
```

So as example app:
```javascript
const merge = require('webpack-merge')
const TerserPlugin = require('terser-webpack-plugin')

const x = merge(
  {
    optimization: {
      minimizer: [new TerserPlugin()]
    }
  },
  {
    optimization: {
      minimizer: [new TerserPlugin()]
    }
  }
)
console.log(x)

// { optimization: { minimizer: [ [TerserPlugin], [TerserPlugin] ] } }
```

**Comment by patricklafrance** [comment]
Yes as you pointed out craco use `webpack-merge` to merge the `configure` object into the resulting webpack config. If it works with `webpack-merge` it should be fine.

Otherwise maybe it's overrided somewhere else? Maybe by a craco plugin?

How do you validate if the resulting webpack config? One way to do it use to use the [craco api](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#createwebpackdevconfig--createwebpackprodconfig) to print out the resulting config.

**Comment by liorfrenkel** [comment]
hey guys, in order to change the terser config, use the plugins section of craco:

```
// craco.config.js
module.exports = {
  plugins: [
    {
      plugin: {
        overrideWebpackConfig: ({
          webpackConfig,
        }) => {
          const minimizerIndex = webpackConfig.optimization.minimizer.findIndex(item => item.options.terserOptions);

          // do not mangle problematic modules of bitcoinjs-lib
          webpackConfig.optimization.minimizer[minimizerIndex].options.terserOptions.mangle = {
            ...webpackConfig.optimization.minimizer[minimizerIndex].options.terserOptions.mangle,
            reserved: ['BigInteger', 'ECPair', 'Point']
          };

          return webpackConfig;
        },
      },
    },
  ],
};
```

here I find the index of the terser plugin by searching for `terserOptions`  
then I use that object to add/override the `reserved` option.  
I hope that helps!

**Comment by patricklafrance** [comment]
@liorfrenkel thank you for your help!

By the way, you should release a craco plugin with this code :)

**Comment by patricklafrance** [comment]
@tmock12 I made a test with:

```
    webpack: {
        configure: {
            optimization: {
                minimizer: [new TerserPlugin({ extractComments: false })]
            }
        }
    },
```

Here's the `optimization.minimizer` section of the resulting webpack config:

```
    "minimizer": [
      {
        "options": {
          "test": {},
          "extractComments": true,
          "sourceMap": true,
          "cache": true,
          "parallel": true,
          "terserOptions": {
            "parse": {
              "ecma": 8
            },
            "compress": {
              "ecma": 5,
              "warnings": false,
              "comparisons": false,
              "inline": 2
            },
            "mangle": {
              "safari10": true
            },
            "keep_classnames": false,
            "keep_fnames": false,
            "output": {
              "ecma": 5,
              "comments": false,
              "ascii_only": true
            }
          }
        }
      },
      {
        "pluginDescriptor": {
          "name": "OptimizeCssAssetsWebpackPlugin"
        },
        "options": {
          "assetProcessors": [
            {
              "phase": "compilation.optimize-chunk-assets",
              "regExp": {}
            }
          ],
          "assetNameRegExp": {},
          "cssProcessorOptions": {
            "map": {
              "inline": false,
              "annotation": true
            }
          },
          "cssProcessorPluginOptions": {}
        },
        "phaseAssetProcessors": {
          "compilation.optimize-chunk-assets": [
            {
              "phase": "compilation.optimize-chunk-assets",
              "regExp": {}
            }
          ],
          "compilation.optimize-assets": [],
          "emit": []
        },
        "deleteAssetsMap": {}
      },
      {
        "options": {
          "test": {},
          "extractComments": false,
          "cache": true,
          "parallel": true,
          "terserOptions": {}
        }
      }
    ],
```

As you can, the native CRA Terser config is the first object and my custom Terser config is the last object of the section.

I guess `wepack-merge` isn't smart enough to understand that the minimizer array contains two instances of the same plugin and he should merge them. Which make sense.

`webpack-merge` support custom functions to [customize the merging strategies of arrays](https://github.com/survivejs/webpack-merge#merge-customizearray-customizeobject-configuration-configuration) I guess CRACO could accept these but I am not sure if this is a better solution than writing a custom CRACO plugin as @liorfrenkel did. What do you think?

By the way, an alternative to write a custom CRACO plugin is to use the function syntax of `webpack.configure`:

```
webpack.configure: (webpackConfig, { env, paths }) => {
   // do your things
  // ...

  // then return an updated webpack config.
  return webpackConfig; 
}
```

Hope this help,

Patrick

**Comment by mkms1104** [comment]
webpack v5 best answer 

... in backtick 

=> minimizer: [`...`, new OptimizeCSSAssetsPlugin({})]

**Comment by instil-spencerc** [comment]
Here is how I was able to get it work using `7.0.0-alpha.7`:

```
module.exports = {
  plugins: [
    {
      plugin: {
        overrideWebpackConfig: ({ webpackConfig }) => {
          // NODE_ENV is always "production" for `craco build`, and we can't change that. 
          // So we use BUILD_ENV instead which we set in the npm script to
          // trigger builds. If there is no BUILD_ENV, then we'll skip all of this.
          const { BUILD_ENV: buildEnv } = process.env;

          const canUpdateTerserPlugin =
            buildEnv === 'development' || buildEnv === 'staging';

          if (!canUpdateTerserPlugin) {
            return webpackConfig;
          }

          // Find the terser plugin by looking for "extractComments"
          const minimizerIndex = webpackConfig.optimization.minimizer.findIndex(
            (item) => item.options.extractComments
          );

          if (minimizerIndex !== -1) {
            let terserPluginOptions =
              webpackConfig.optimization.minimizer[minimizerIndex].options
                .minimizer.options;

            terserPluginOptions = {
              ...terserPluginOptions,
              keep_classnames: true,
              keep_fnames: true,
            };

            webpackConfig.optimization.minimizer[
              minimizerIndex
            ].options.minimizer.options = terserPluginOptions;
          }

          return webpackConfig;
        },
      },
    },
  ],
};
```
Usage in `package.json`:
```
"scripts": {
    "build": "BUILD_ENV=development craco build"
}
```

**Comment by qeleb** [comment]
> @instil-spencerc that was really helpful.

In case someone else using Craco 7 shows up here...
This is my configuration to shrink the bundle with some optimizations in Terser. If your code isn't too crazy, you should be able to just drop this in to a `craco.config.ts` file and have a dramatically smaller bundle.


```typescript
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'

module.exports = {
  babel: {
    presets: [
      [
        '@babel/preset-env',
        {
          loose: true
        }
      ]
    ]
  },
  webpack: {
    alias: {
      react: 'preact/compat',
      'react-dom': 'preact/compat'
    },
    plugins: process.env.ANALYZE === 'true' ? [new BundleAnalyzerPlugin()] : []
  },
  plugins: [
    {
      plugin: {
        overrideWebpackConfig: ({ webpackConfig }) => {
          // Find the terser plugin by looking for "extractComments"
          const i = webpackConfig.optimization.minimizer.findIndex(
            x => x.options.extractComments
          )
          if (i !== -1) {
            webpackConfig.optimization.minimizer[i].options.minimizer.options =
              {
                ...webpackConfig.optimization.minimizer[i].options.minimizer
                  .options,
                compress: {
                  ecma: 8,
                  // Disabled because it breaks valid code: https://github.com/facebook/create-react-app/issues/5250
                  // Pending further investigation: https://github.com/terser-js/terser/issues/120
                  inline: 2,
                  passes: 3,
                  pure_getters: true,
                  unsafe: true,
                  warnings: false
                },
                mangle: {
                  safari10: false // Use this if you don't care to support iOS/Safari <=11
                },
                output: {
                  // On because emoji+regex are broken https://github.com/facebook/create-react-app/issues/2488
                  ascii_only: true,
                  comments: false,
                  ecma: 8,
                  wrap_func_args: false
                }
              }
          }
          return webpackConfig
        }
      }
    }
  ]
}
```

This part is optional.. It's helpful to see what's taking up the space in your webpack bundles.
`yarn add webpack-bundle-analyzer`
```json
"scripts": {
    ...
  "analyze": "cross-env ANALYZE=true yarn run build",
    ...
},
```

**Comment by paltry-pleuroma** [comment]
> > @instil-spencerc that was really helpful.
> 
> In case someone else using Craco 7 shows up here... This is my configuration to shrink the bundle with some optimizations in Terser. If your code isn't too crazy, you should be able to just drop this in to a `craco.config.ts` file and have a dramatically smaller bundle.
> 
> ```ts
> import { CracoConfig } from '@craco/craco/dist/types/config'
> import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'
> 
> module.exports = {
>   babel: {
>     presets: [
>       [
>         '@babel/preset-env',
>         {
>           loose: true
>         }
>       ]
>     ]
>   },
>   webpack: {
>     alias: {
>       react: 'preact/compat',
>       'react-dom': 'preact/compat'
>     },
>     plugins: process.env.ANALYZE === 'true' ? [new BundleAnalyzerPlugin()] : []
>   },
>   plugins: [
>     {
>       plugin: {
>         overrideWebpackConfig: ({ webpackConfig }) => {
>           const terser: any = webpackConfig?.optimization?.minimizer?.find(
>             x => (x as any).options.extractComments // Find Terser: lookup "extractComments"
>           )
>           if (terser) {
>             terser.options.extractComments = false // Removes 54 bytes of LICENSE
>             terser.options.minimizer.options = {
>               ...terser.options.minimizer.options,
>               compress: {
>                 ecma: 8, // Not 5, because I don't care to support IE11
>                 inline: 2, // Breaks code according to CRA
>                 passes: 3,
>                 pure_getters: true,
>                 unsafe: true, // Remove this if it causes errors (it might)
>                 warnings: false
>               },
>               mangle: {
>                 safari10: false // Use this if you don't care to support iOS/Safari <=11
>               },
>               output: {
>                 // On because emoji+regex are broken https://github.com/facebook/create-react-app/issues/2488
>                 ascii_only: true,
>                 comments: false,
>                 ecma: 8, // Not 5, because I don't care to support IE11
>                 wrap_func_args: false
>               }
>             }
>           }
>           return webpackConfig
>         }
>       }
>     }
>   ]
> } as CracoConfig
> ```
> 
> This part is optional.. It's helpful to see what's taking up the space in your webpack bundles. `yarn add webpack-bundle-analyzer`
> 
> ```json
> "scripts": {
>     ...
>   "analyze": "cross-env ANALYZE=true yarn run build",
>     ...
> },
> ```

This is great, thanks! Quick note: the config import gives TS errors but my IDE found it: `import {CracoConfig} from "@craco/types";`

**Comment by paltry-pleuroma** [comment]
> > > @instil-spencerc that was really helpful.
> > 
> > 
> > In case someone else using Craco 7 shows up here... This is my configuration to shrink the bundle with some optimizations in Terser. If your code isn't too crazy, you should be able to just drop this in to a `craco.config.ts` file and have a dramatically smaller bundle.
> > ```ts
> > import { CracoConfig } from '@craco/craco/dist/types/config'
> > import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'
> > 
> > module.exports = {
> >   babel: {
> >     presets: [
> >       [
> >         '@babel/preset-env',
> >         {
> >           loose: true
> >         }
> >       ]
> >     ]
> >   },
> >   webpack: {
> >     alias: {
> >       react: 'preact/compat',
> >       'react-dom': 'preact/compat'
> >     },
> >     plugins: process.env.ANALYZE === 'true' ? [new BundleAnalyzerPlugin()] : []
> >   },
> >   plugins: [
> >     {
> >       plugin: {
> >         overrideWebpackConfig: ({ webpackConfig }) => {
> >           const terser: any = webpackConfig?.optimization?.minimizer?.find(
> >             x => (x as any).options.extractComments // Find Terser: lookup "extractComments"
> >           )
> >           if (terser) {
> >             terser.options.extractComments = false // Removes 54 bytes of LICENSE
> >             terser.options.minimizer.options = {
> >               ...terser.options.minimizer.options,
> >               compress: {
> >                 ecma: 8, // Not 5, because I don't care to support IE11
> >                 inline: 2, // Breaks code according to CRA
> >                 passes: 3,
> >                 pure_getters: true,
> >                 unsafe: true, // Remove this if it causes errors (it might)
> >                 warnings: false
> >               },
> >               mangle: {
> >                 safari10: false // Use this if you don't care to support iOS/Safari <=11
> >               },
> >               output: {
> >                 // On because emoji+regex are broken https://github.com/facebook/create-react-app/issues/2488
> >                 ascii_only: true,
> >                 comments: false,
> >                 ecma: 8, // Not 5, because I don't care to support IE11
> >                 wrap_func_args: false
> >               }
> >             }
> >           }
> >           return webpackConfig
> >         }
> >       }
> >     }
> >   ]
> > } as CracoConfig
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This part is optional.. It's helpful to see what's taking up the space in your webpack bundles. `yarn add webpack-bundle-analyzer`
> > ```json
> > "scripts": {
> >     ...
> >   "analyze": "cross-env ANALYZE=true yarn run build",
> >     ...
> > },
> > ```
> 
> This is great, thanks! Quick note: the config import gives TS errors but my IDE found it: `import {CracoConfig} from "@craco/types";`

Something else to consider: this setup does not preserve `comparisons: false` in terserOptions.compress (could break code), see [CRA webpack config comment](https://github.com/facebook/create-react-app/blob/0a827f69ab0d2ee3871ba9b71350031d8a81b7ae/packages/react-scripts/config/webpack.config.js#L279C15-L279C34).  I prevented this by using lodash merge function to deeply merge the default config instead of splatting it top-level. I also removed the preact stuff which is a bit too specific to make this a generic drop-in solution.
