### ISSUE TITLE
Support custom CRA paths

### ISSUE THREAD

**Issue by patricklafrance** [sharegate/craco#46]
Add a section to customize the CRA paths:

    dotenv: resolveOwn('template/.env'),
    appPath: resolveApp('.'),
    appBuild: resolveOwn('../../build'),
    appPublic: resolveOwn('template/public'),
    appHtml: resolveOwn('template/public/index.html'),
    appIndexJs: resolveModule(resolveOwn, 'template/src/index'),
    appPackageJson: resolveOwn('package.json'),
    appSrc: resolveOwn('template/src'),
    appTsConfig: resolveOwn('template/tsconfig.json'),
    yarnLockFile: resolveOwn('template/yarn.lock'),
    testsSetup: resolveModule(resolveOwn, 'template/src/setupTests'),
    proxySetup: resolveOwn('template/src/setupProxy.js'),
    appNodeModules: resolveOwn('node_modules'),
    publicUrl: getPublicUrl(resolveOwn('package.json')),
    servedPath: getServedPath(resolveOwn('package.json')),
    // These properties only exist before ejecting:
    ownPath: resolveOwn('.'),
    ownNodeModules: resolveOwn('node_modules'),
    appTypeDeclarations: resolveOwn('template/src/react-app-env.d.ts'),
    ownTypeDeclarations: resolveOwn('lib/react-app.d.ts'),

**Comment by tzarger** [comment]
+1

**Comment by patricklafrance** [comment]
Oh Well fuck me, I lost all my changes :(

Anyway.

**Comment by StruggleQueen** [comment]
I'm already confused. I know I've been hacked and the more I've done to
find the source and stop it, the worse I think I've made it. I'm sorry for
whatever I caused you. Thanks for reaching out.

**Comment by joernroeder** [comment]
@patricklafrance what happened? so this is is still not possible right?

**Comment by patricklafrance** [comment]
@joernroeder yep as far as I know, it's still not possible.

**Comment by joernroeder** [comment]
@patricklafrance ok thanks. will stick with `react-app-rewired` for now where path rewriting works easily.

**Comment by patricklafrance** [comment]
@joernroeder do you know how it's done with react-app-rewired?

**Comment by patricklafrance** [comment]
The problem for me, is those hardcore paths in the jest config (mostly "/src")

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/utils/createJestConfig.js
