### ISSUE TITLE
Craco start and craco build causing different css ordering

### ISSUE THREAD

**Issue by PatchOnKnee** [sharegate/craco#57]
We recently moved over to craco from react-app-rewired, in conjunction with ant-design. However the css is applied differently when running locally compared to running the completed build. Below is the contents of the craco.config.js file. 
`test`
` const CracoAntDesignPlugin = require('craco-antd');`
`const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');`
`const WebpackBar = require('webpackbar');`
`module.exports = {`
 `    plugins: [{ plugin: CracoAntDesignPlugin }],`
  `    webpack: {`
   `         plugins: [`
    `          new WebpackBar({ profile: true }),`
    `        ],`
  `    },`
`};`

Is this the correct way to ensure that the ant-d styles will be applied last, or have I missed something?

**Comment by patricklafrance** [comment]
Any idea @ndbroadbent ?

**Comment by ndbroadbent** [comment]
Hi, I can have a look at this. I've opened a new issue in craco-antd repo, which might be a better place to discuss that: https://github.com/FormAPI/craco-antd/issues/12

**Comment by StruggleQueen** [comment]
Thank you. To be honest, I'm confused anyways and I have no idea why.

**Comment by patricklafrance** [comment]
Closing this since it's handled in a different repository
