### ISSUE TITLE
Environment in `dotenv` files seems not correctly applied.

### ISSUE THREAD

**Issue by yp** [sharegate/craco#58]
I am setting `PUBLIC_URL` on `.env.production` but it seems that `.env*` files are not read while building (and overriding) the `webpack` configuration. Indeed, the configuration of the `InterploateHtmlPlugin` does not "see" the variables I set on these files, while the message at the end of the build (`The project was built assuming it is hosted at /MY_PUBLIC_URL`) correctly reports it.
If I add `require(resolveConfigFilePath("env.js"));` before line https://github.com/sharegate/craco/blob/c4e8dd40aa875fcef02467dac444122bbf241956/packages/craco/lib/cra.js#L20
everything works.
Indeed, the original script `react-scripts/scripts/build.js` loads the environment before building the configuration (see https://github.com/facebook/create-react-app/blob/45bc6280d109b7e353ffaa497a0352c9d040c36d/packages/react-scripts/scripts/build.js#L22).

**Comment by patricklafrance** [comment]
Hi @yp

I will see what I can do.

Thank you

**Comment by patricklafrance** [comment]
Available with https://www.npmjs.com/package/@craco/craco/v/3.4.0

**Comment by abenhamdine** [comment]
thx @patricklafrance !
:dancer:

**Comment by ajaij** [comment]
@patricklafrance how do I access the variables inside my .env inside craco.config.js ?

**Comment by ajaij** [comment]
@patricklafrance @abenhamdine how can I access the variables in my .env from craco.config.js ? Currently am getting the value as undefined.


```
/* .env */
REACT_APP_FOO="bar"

/* craco.config.js */
console.log('env....', process.env.REACT_APP_FOO);  // getting undefined here
```

**Comment by trickpattyFH20** [comment]
https://github.com/djdmbrwsk/dotenv-cra
