### ISSUE TITLE
How to use Astroturf and Linaria like css in js tool

### ISSUE THREAD

**Issue by sysleaf** [sharegate/craco#63]
Hi,

Thanks for this awesome tool.

Can you please help, setting up [linaria](https://github.com/callstack/linaria) . I think we need to modify Webpack loader(Linaria loader should load before babel-loader) but not sure how to do this.

**Comment by d3dc** [comment]
You'd want to write an `overrideWebpackConfig` plugin using the [utilities that come with craco](https://github.com/sharegate/craco/blob/master/packages/craco/README.md#utility-functions)

```
const { addBeforeLoader, loaderByName } = require("@craco/craco")

const linariaLoader = {
    loader: require.resolve('linaria/loader'),
    options: {
        sourceMap: process.env.NODE_ENV !== 'production',
    },
}

addBeforeLoader(webpackConfig, loaderByName("babel-loader"), linariaLoader)

```

**Comment by sysleaf** [comment]
Thank you so much for the suggestion. I will definity try it out and post feedback.

**Comment by patricklafrance** [comment]
I will close this issue since it seems to resolved!
