### ISSUE TITLE
Overide webpack entry point ?

### ISSUE THREAD

**Issue by melMass** [sharegate/craco#66]
Craco is great thanks a lot.

I would like to override `create-react-app` default `./src/index.js` entry point.
It is possible?

Thanks

**Comment by patricklafrance** [comment]
Hi @melMass 

Yes it could be done when https://github.com/sharegate/craco/issues/46 is done.

As of now no.

Meanwhile, what I do in my projects:

I create the required app/src/index.js file

And in the `index.js` file I import my actual entry point.

```js
// Even with craco it's quite difficult to update the create-react-app entry point, this is a workaround.

import "./app/index";
```

**Comment by n3ps** [comment]
What if the entry file you want to use is on a directory on the same level as CRA's expected `src`? It throws an error about Relative imports outside of src/ are not supported.

**Comment by JaapWeijland** [comment]
Is this implemented? I don't see a mention in the docs how the overwrite the entry point.
