### ISSUE TITLE
craco broken with react-script 2.1.2

### ISSUE THREAD

**Issue by abenhamdine** [sharegate/craco#67]
[Bug]Error: Cannot find module './node_modules/react-scripts/config/webpack.config.dev' with react-script v2.1.2

see https://github.com/sharegate/craco/issues/61 for more context, which has been closed by the OP but not fixed.

Corresponding PR : https://github.com/sharegate/craco/pull/62

**Comment by ltfschoen** [comment]
let's just stick to one Github issue per issue, https://github.com/sharegate/craco/issues/61 has been re-opened

**Comment by abenhamdine** [comment]
I close this one in favor of #61
