### ISSUE TITLE
Simple Example with raw-loader

### ISSUE THREAD

**Issue by melMass** [sharegate/craco#69]
Can you please provide the most simple example to use [`raw-loader`](https://github.com/webpack-contrib/raw-loader) for `.frag` files using craco ?

Thanks

here is my non working test:
```js
/* craco.config.js */
module.exports = {
  webpack: {
    alias: {},
    plugins: [],
    mode: 'extends',
    configure: { 
      module: {          
        rules: [
          {
            test: /\.frag$/,
            use: 'raw-loader'
          }
        ]
      }, 
    }
  },
}

```

**Comment by patricklafrance** [comment]
Hi @melMass 

The problem is that your rule is added after the `file-loader` which is CRA fallback for every resources that are not handled by any other specific loader.

Here's a comment from CRA webpack config

```
// ** STOP ** Are you adding a new loader?
// Make sure to add the new loader(s) before the "file" loader.
```

The solution is to add your loader before the `file-loader`.

You can do this 2 ways with the help of `craco` utility function [addBeforeLoader](https://github.com/sharegate/craco/blob/master/packages/craco/README.md#addbeforeloader):

By using the function override version of configure:

```
module.exports = {
  webpack: {
    configure: function(webpackConfig) {
         const fragLoader = {
            test: /\.frag$/,
            use: ['raw-loader']
         };

         addBeforeLoader(webpackConfig, loaderByName("file-loader"), fragLoader );

         return webpackConfig;
    }
  },
}
```

Or by creating a craco plugin for raw-loader (which is I think the best way :)). Something like `craco-plugin-add-raw-loader` with plugin options:

```
{
    test: "regex of file to handle"
}
```

[How to a craco develop-a-plugin](https://github.com/sharegate/craco/blob/master/packages/craco/README.md#)

Hope it helps!

Patrick

**Comment by melMass** [comment]
@patricklafrance Thanks a lot! 
I'll go the plugin way right now and report back here my results later today.

**Comment by melMass** [comment]
It was easier than expected!!
Here is the plugin:

```js
/* craco-plugin-raw-loader.js */

const { loaderByName, addBeforeLoader } = require('@craco/craco')

module.exports = {
  overrideWebpackConfig: ({
    webpackConfig, cracoConfig, pluginOptions, context: { env, paths } 
  }) => {

    const rawLoader = {
      test: pluginOptions.test,
      use: [ 'raw-loader' ]
    }

    addBeforeLoader(webpackConfig, loaderByName('file-loader'), rawLoader)

    return webpackConfig
  }
}
```

and to use it in your config (here to detect `.frag` files):

```js
/* craco.config.js */

module.exports = {
  webpack: {
    plugins: [
     { plugin: rawWebpackConfigPlugin, options: { test: /\.frag$/ } }
  ]
}
```

```

**Comment by melMass** [comment]
Is there a recommended way to package plugins to npm?

**Comment by patricklafrance** [comment]
@melMass no nothing special for now, maybe exception the name of the package that should start with "craco-".

You can find an example of a plugin here: https://www.npmjs.com/package/craco-antd

**Comment by melMass** [comment]
Thanks again.

Here is the plugin [craco-raw-loader](https://www.npmjs.com/package/craco-raw-loader)

**Comment by patricklafrance** [comment]
Thank you @melMass!

I added it to the plugin list!

**Comment by melMass** [comment]
Cool
if you are interested I just made another one along the same concept:

[craco-base64-inline-loader](https://github.com/melMass/craco-base64-inline-loader)

**Comment by AlexBronz** [comment]
Hi,
Can I ask a dumb question? How do I use this craco-base64-inline-loader along with create-react-app scripts? should I just specify it in package.json like "build" : react-scripts craco.config.js? Thanks!

**Comment by melMass** [comment]
@AlexBronz You can find a sample use case for font files on it's repo:

### craco.config.js
```js
const base64Loader = require('craco-base64-inline-loader')

module.exports = {
  webpack: {
    plugins: [
     { plugin: base64Loader,
       options: {
         test: /\.(ttf|eot|otf|svg|woff(2)?)$/i ,
         limit: 1000 // <-- Optional
         }
     }
  ]
}
```

If you have trouble, post an issue on the repo itself. ;)
