### ISSUE TITLE
Is it possible to console.log to see config?

### ISSUE THREAD

**Issue by kmcaloon** [sharegate/craco#71]
I would like to check out the webpackConfig, env, and paths values for the configure option but there doesn't seem to be an easy way to see them.  I am trying to understand these configurations options and would like to add a resolve plugin so I'm trying to see what is available here...

```
module.exports = {
  ...,
  configure: ( webpackConfig, { env, paths } ) => {
    console.log( webpackConfig );
  }
```

**Comment by kmcaloon** [comment]
So the first problem was I was adding the configure option to the default export instead of the webpack object. In order to view the console.log I just broke the build by not returning the webpackConfig.  

```
module.exports = {
  webpack: {
    ...,
    configure: ( webpackConfig, { env, paths } ) => {
      console.log( webpackConfig );
      return null;
    }
}
```

**Comment by yairopro** [comment]
@kmcaloon you saved my day! 😻
