### ISSUE TITLE
I don't understand how to translate this code from react-app-rewired to craco

### ISSUE THREAD

**Issue by frederikhors** [sharegate/craco#72]
I don't understand how to translate this code from react-app-rewired to craco:

- config-overrides.js:

```js
const { injectBabelPlugin } = require('react-app-rewired')

module.exports = function override (config, env) {
  config = injectBabelPlugin('graphql-tag', config)
  return config
}
```

Maybe it's just me but I really don't understand this simply problem.

**How to?**

**Comment by patricklafrance** [comment]
Hi @frederikhors 

You can configure custom babel plugins with

```
module.exports = {
     babel: {
        plugins: [
             ["graphql-tag", config]
        ]
     }
}
```

The full documentation is available here: https://github.com/sharegate/craco/blob/master/packages/craco/README.md#configuration-overview

Hope this helps!
