### ISSUE TITLE
Bug - needs more inspection 

### ISSUE THREAD

**Issue by serus22** [sharegate/craco#74]
Hi, i found an issue when i tried to crate webpack alias

i had to use `overrideCracoConfig` instead of `overrideWebpackConfig` 

more details: 

https://github.com/HasanAyan/craco-plugin-react-hot-reload/pull/3/commits/267905a1b5105ff52763288bb7077fceefe452a7#diff-168726dbe96b3ce427e7fedce31bb0bcR42

https://github.com/HasanAyan/craco-plugin-react-hot-reload/pull/3/commits/41d8e30a1b76516b73795e7ee5d93175a29e342f#diff-168726dbe96b3ce427e7fedce31bb0bcR29

if i used overrideWebpackConfig version directly in craco config, it was working, but in plugin it does not
i will try to inspect problem in few days

**Comment by patricklafrance** [comment]
Hi @serus22 

Thank you, let me know what you find out.

**Comment by patricklafrance** [comment]
Hi @serus22 

Any news on this?

**Comment by patricklafrance** [comment]
Closing this issue since there is no comments for 25 days
