### ISSUE TITLE
Add a quick way to disable tslint for typescript projects

### ISSUE THREAD

**Issue by mgcrea** [sharegate/craco#75]
Not sure if there is an easy way to do this but I tried `{eslint: {enable: false}}` and `{tslint: {enable: false}}`.

Here is how I used to do it with rewired:

```js
const EXCLUDED_PLUGINS = ['ForkTsCheckerWebpackPlugin'];
config.plugins = config.plugins.filter(plugin => !EXCLUDED_PLUGINS.includes(plugin.constructor.name));
```

**Comment by patricklafrance** [comment]
Hi @mgcrea 

I dont personally use TypeScript so I am not familiar with how all the tooling works.

Looks like CRA doesn't come out of the box with the loader `tslint-loader`. From your code sample I guess the lintings come from the `ForkTsCheckerWebpackPlugin` webpack plugin.

The documentation of [ForkTsCheckerWebpackPlugin](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin) say that to enable linting you should set `tslint` to **true** which is not the case for CRA.

```
        new ForkTsCheckerWebpackPlugin({
          typescript: resolve.sync('typescript', {
            basedir: paths.appNodeModules,
          }),
          async: isEnvDevelopment,
          useTypescriptIncrementalApi: true,
          checkSyntacticErrors: true,
          tsconfig: paths.appTsConfig,
          reportFiles: [
            '**',
            '!**/*.json',
            '!**/__tests__/**',
            '!**/?(*.)(spec|test).*',
            '!**/src/setupProxy.*',
            '!**/src/setupTests.*',
          ],
          watch: paths.appSrc,
          silent: true,
          // The formatter is invoked directly in WebpackDevServerUtils during development
          formatter: isEnvProduction ? typescriptFormatter : undefined,
        }),
```

I would like to support it with `craco` but I dont understand your use case wll. It looks to me that you want to disable TypeScript type checking and not `tslint`, im I wrong?

That being said, the equivalent for `craco` of  what you were doing with rewired is:

```
module.exports = {
    webpack: {
       configure: (webpackConfig, { env, paths }) => { 
           const EXCLUDED_PLUGINS = ['ForkTsCheckerWebpackPlugin'];

           webpackConfig.plugins = webpackConfig.plugins.filter(plugin => !EXCLUDED_PLUGINS.includes(plugin.constructor.name));

           return webpackConfig; 
        }
    }
};
```

Hope it helps!

**Comment by mgcrea** [comment]
@patricklafrance Thanks for the quick reply, I was indeed talking about disabling typescript type checking in webpack's pipeline, it already runs inside vscode and I don't need to have it run twice, moreover I find it really slows down development (can't have a render unless typechecking passes).

I don't really care about `tslint` and I'm not using it (looks like `ForkTsCheckerWebpackPlugin` supports it but I don't think CRA uses it).

Your solution works. Might still be interesting to have a more user-friendly option.

Thanks!

**Comment by patricklafrance** [comment]
@mgcrea you are right, keep this issue open, I will add a more user-friendly option.

**Comment by Dakkers** [comment]
I did something similar recentlyfor a different plugin:

```
    webpack: {
      plugins: [
        new webpack.IgnorePlugin(/^\.\/(?!en)(.+)$/, /validatorjs\/src\/lang/),
        new ScriptExtHtmlWebpackPlugin({
          defaultAttribute: 'defer'
        })
      ],
      configure: (webpackConfig, { env, paths }) => {
        const htmlWebpackPluginInstance = webpackConfig.plugins.find((p) => p instanceof HtmlWebpackPlugin);
        if (htmlWebpackPluginInstance) {
          htmlWebpackPluginInstance.options.inject = 'head';
        }

        return webpackConfig;
      }
    }
```

using `instanceof` worked for me, though it's not much prettier (feels a bit less janky)

**Comment by patricklafrance** [comment]
@mgcrea available with https://www.npmjs.com/package/@craco/craco/v/3.6.0

You can disable typescript type checking by doing

```
    typescript: {
        enableTypeChecking: false
    }
```

**Comment by socketpair** [comment]
@patricklafrance Just WHERE to write this ?!
