### ISSUE TITLE
Why install craco as dependencies but not devDependencies?

### ISSUE THREAD

**Issue by zhaoyao91** [sharegate/craco#76]
Why install craco as dependencies but not devDependencies?

**Comment by patricklafrance** [comment]
@ndbroadbent can you answer this one?

**Comment by zhaoyao91** [comment]
I tried to install it as devDependence. By now I didn't find any problem.

**Comment by patricklafrance** [comment]
@zhaoyao91 same here. The documentation have been updated to install craco as dependencies after a comment made by @ndbroadbent but I dont remember the specific reason.

**Comment by patricklafrance** [comment]
Thank you @ndbroadbent

**Comment by takhello** [comment]
It seems that react is not very sound, not very willing to use
