### ISSUE TITLE
Support CRA v3

### ISSUE THREAD

**Issue by kMeillet** [sharegate/craco#83]
CRA v3 is now released. It would be awesome to have craco support it. But i don't know exactly what this update will break in craco.

If someone want to give a shot 👍  .

**Comment by patricklafrance** [comment]
I run a few test and everything seems to run fine.

Let me know if you find anything!

**Comment by patricklafrance** [comment]
Would be nice to investigate if something should be added to craco in regards of:

- New TypeScript linting support
- browserslist support in @babel/preset-env

**Comment by PutziSan** [comment]
Hi,
It seems like you can't overwrite the typescript-rules:

![image](https://user-images.githubusercontent.com/13392042/56650167-c8ade080-6686-11e9-98df-02c35ad17af6.png)

**Comment by patricklafrance** [comment]
Hi @PutziSan 

Does it work for non typesscript rules?

Thank you

Patrick

**Comment by batusai513** [comment]
For me, it is working except for the craco-babel-loader plugin, I've made a PR to update it https://github.com/rjerue/craco-babel-loader/pull/2

**Comment by atdrago** [comment]
@PutziSan I was having the same issue with the same rule. I finally figured out you need to use `overrides` in your eslint config. I think this is because that's [where eslint-config-react-app adds that rule](https://github.com/facebook/create-react-app/blob/57ef103440c24e41b0d7dc82b7ad7fc1dc817eca/packages/eslint-config-react-app/index.js#L55). 

I was able to override `@typescript-eslint/no-unused-vars` after I added an `overrides` section to my eslint config:
```js
{
  "overrides": {
    "files": [
      "**/*.ts",
      "**/*.tsx"
    ],
    "rules": {
      // @typescript-eslint rules
      "@typescript-eslint/no-unused-vars": "off"
    }
  },
  "rules": {
    // other rules
  }
}
```

**Comment by kantuni** [comment]
Any news?

**Comment by kantuni** [comment]
Any updates on this issue?

**Comment by patricklafrance** [comment]
Hi @kantuni is it an issue with craco or eslint? Does @atdrago works for you?

**Comment by kantuni** [comment]
Hey @patricklafrance, 
Craco works perfectly fine with 2.x. I was just curious when will the support for 3.x come out?

**Comment by patricklafrance** [comment]
@kantuni Craco already support 3.x. If there is something that is missing, let me know!

**Comment by kantuni** [comment]
Cool. Thanks!

P.S. Your README says "Create React App Configuration Override is an easy and comprehensible configuration layer for create-react-app v2."

**Comment by patricklafrance** [comment]
@kantuni oops, thank you I will update it!
