### ISSUE TITLE
.env.production not applied

### ISSUE THREAD

**Issue by LentnerStefan** [sharegate/craco#84]
After updating from craco 3.6.0 to 4.0.0, I noticed the PUBLIC_URL env variable ( set in .env.production ) is not applied anymore (although there's a message at the end of the build indicating the correct one  => `The project was built assuming it is hosted at /PUBLIC_URL`).

The issue  is quite similar to this one : https://github.com/sharegate/craco/issues/58. 

I tried to look at the commits between 3.6.0 & 4.0.0 but couldn't find where the problem comes from :/

**Comment by patricklafrance** [comment]
Hi @LentnerStefan 

Thank you for reporting the problem.

I am also surprised that the changes affect this. I will have a look soon.

Patrick

**Comment by onlyann** [comment]
I can confirm that none of the variables defined in  _.env_ and _.env.*_  files are merged anymore. Outputting `process.env`  from _craco.config.js_ shows the variables in `process.env` in v3.6.0 but nothing from 4.0.0 onwards.

**Comment by umartopia** [comment]
By any chance you are using the latest env-cmd npm package? if that is the case, then you might have to pass -f switch along with env command.

**Comment by onlyann** [comment]
I am not explicitly using `env-cmd` package, only the environment variable feature that is built in Create React App.

**Comment by patricklafrance** [comment]
Fix with 5.2: https://www.npmjs.com/package/@craco/craco/v/5.2.0
