### ISSUE TITLE
[Question] How can I use .eslintignore file?

### ISSUE THREAD

**Issue by palindrom615** [sharegate/craco#85]
Craco works amazing with my eslintrc and file mode. But is there any way to exclude files from eslint?

For now, it seems both `.eslintignore` file and `eslintIgnore` prop of `package.json` do not work.

**Comment by patricklafrance** [comment]
Hi @palindrom615 

I thought it works. I will need to investigate. My guess is that we need to "activate" a specific option on the loader.

**Comment by palindrom615** [comment]
Hi @patricklafrance , thanks for the response.

I found this was not a craco issue. I'll leave my case FYI.

I have missed eslint-loader ignore option(which makes me confused because it is not documented in eslint-loader repo) which is false default in CRA. https://github.com/facebook/create-react-app/blob/394e385d5e25705ebd9f82e90958f6f207a5c315/packages/react-scripts/config/webpack.config.js#L325

```javascript
const { ESLINT_MODES } = require("@craco/craco");
const CracoAntDesignPlugin = require("craco-antd");

module.exports = {
  eslint: {
    mode: ESLINT_MODES.file,
    // Added!
    loaderOptions: eslintOptions => {
      return { ...eslintOptions, ignore: true };
    }
  },
  plugins: [{ plugin: CracoAntDesignPlugin }]
};
```

I overrode ignore of loaderOptions and it works great!

**Comment by patricklafrance** [comment]
Thank you for your solution @palindrom615.

I will update craco to set to ignore option to true by default
