### ISSUE TITLE
Does latest version work with ts-loader

### ISSUE THREAD

**Issue by Anoupz** [sharegate/craco#90]
Hi, 

Thanks for the amazing library. I started to use this when the version was `3.2.3` and react-script at `2.1.3`. At that time CRA didn't have support for typescript. Hence I configured to use ts-loader to create my project in typescript with overriding webpack config
```
overrideWebpackConfig: ({ webpackConfig, context: { env, paths } }) => {
          const {
            match: { loader: tsLoader }
          } = getLoader(webpackConfig, loaderByName('ts-loader'));
          tsLoader.options = {
            ...tsLoader.options,
            getCustomTransformers: () => ({
              before: [
                tsImportPluginFactory({
                  libraryDirectory: 'es',
                  libraryName: 'antd',
                  style: true
                })
              ]
            })
          };
```
Does the latest version support use of ts-loader? I am not a big fan of babel support for typescript as it still doesn't support most features and every time I need to look for babel plugin to make sure the transpilation works.

**Comment by patricklafrance** [comment]
Hi @Anoupz 

Yes CRACO support TypeScript.

**Comment by Anoupz** [comment]
Hi @patricklafrance ,

But the latest version when using with react-scripts-ts doesn't have any loader by name `ts-loader`.

I get the below error when using the same config as before
 Cannot destructure property `loader` of 'undefined' or 'null'.
    at Object.overrideWebpackConfig

**Comment by patricklafrance** [comment]
Hi @Anoupz 

I am not sure how they do it, you should ask in react-script-ts repository or CRA. CRACO doesn't remove or add any loaders from the original webpack configuration.

**Comment by Anoupz** [comment]
Hi @patricklafrance,

Thanks for the update. I believe with version 5 reactscripts path is deprecated. Hence I am sticking with version 3.2.3 and upgraded react-script and react-scripts-ts to `3.0.1` and `4.0.8` respectively. It's working fine now.

**Comment by patricklafrance** [comment]
Hi @Anoupz 

Oh sorry, I think I understand your question now.

The original reactscripts path has been deprecated, the new way to configure it is through the craco.config.js file: https://github.com/sharegate/craco/blob/master/packages/craco/README.md#configuration-overview

To use `react-scripts-ts` you can configure it like this

```
module.exports = {
    reactScriptsVersion: "react-scripts-ts"
};
```

Hope it helps!

Patrick

**Comment by Anoupz** [comment]
Hi @patricklafrance,

Thanks, totally missed this in the doc. but still, there would be a problem as craco looks for webpack.config.js but react-scripts-ts has `webpack.config.dev.js` and `webpack.config.prod.js`. Hence the craco start fails. Do you happen to have a way to work around that?

**Comment by patricklafrance** [comment]
Hi @Anoupz 

I added a fix to fallback on the 2.* filenames if webpack.config.js doesn't exists.

It's available in 5.2.2

https://www.npmjs.com/package/@craco/craco/v/5.2.2

**Comment by Anoupz** [comment]
Hi @patricklafrance 

I just tried. Got error on `craco start`

    return require(filepath)("development");
                            ^

TypeError: require(...) is not a function.

Note: I don't use any babel configurations.

**Comment by patricklafrance** [comment]
Oops sorry, fixed in 5.2.3

**Comment by Anoupz** [comment]
@patricklafrance Awesome that worked thanks

**Comment by socketpair** [comment]
So just how to tune options of ts-loader using craco ?! in 2021 ?
