### ISSUE TITLE
How to reconfigure a rule?

### ISSUE THREAD

**Issue by adi518** [sharegate/craco#91]
So, I'm a bit puzzled tbh. It seems like I can override `css-loader` options, but not the actual rule with the `test` property and all. I used the following snippet to extend CRA in Storybook 5. How can I rewrite this for Craco?

```js
const sassRuleIndex = config.module.rules.findIndex(
  rule => rule.test.source === /\.(scss|sass)$/.source
)

if (sassRuleIndex === -1) {
  throw new Error('Cannot find sass rule in Webpack configuration.')
}

config.module.rules[sassRuleIndex] = {
  test: /\.(scss|sass)$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {        
        modules: true,
        importLoaders: 1,
        localIdentName: 'kn-[name]__[local]___[hash:base64:5]'
      }
    },
    'sass-loader'
  ],
  include: path.resolve(__dirname, '../')
}
```

With some exploring, I noticed I can mutate the config in a similar way, but it seems a bit more nested with a strange `oneOf` property that has all the actual rules.

**Comment by patricklafrance** [comment]
Hi @adi518 

To extends an existing webpack loader you can use  `webpack.configure`.

```
module.exports = {
    webpack: {
        configure: (webpackConfig, { env, paths }) => {
             // do you thing...
 
             return webpackConfig;
        }
    }
};
```

More info available at: https://github.com/sharegate/craco/blob/master/packages/craco/README.md#configuration-overview

Hope it helps!

Patrick

**Comment by adi518** [comment]
Thanks. I basically wanted to set all `css-loader` instances with `modules=true`, instead of having to rename existing CSS files to `[filename].module.css`, which seems like an awkward solution from Facebook (segregating CSS modules into its own extension). AFAICS, the only drawback of having `modules=true` is the need to to wrap your global CSS with the `:global` selector, but it's negligible. :+1:

**Comment by patricklafrance** [comment]
You can look at a "kind of" sample there:

https://github.com/sharegate/craco/blob/master/packages/craco/lib/features/style/css.js

The `getLoaders` function is available to the `craco.config.js` file.

More info here:

https://github.com/sharegate/craco/blob/master/packages/craco/README.md#utility-functions
