### ISSUE TITLE
How to track down the code line

### ISSUE THREAD

**Issue by silencej** [sharegate/craco#97]
I am having the problem to add polyfill support (e.g. support old Chrome and IE11 etc).

I want to use core-js. relay-compiler demands core-js2, while using core-js2, I come across this:

```
[craco] =============
[craco] Failed to compile.
[craco] 
[craco] ./src/index.tsx
[craco] Module not found: Can't resolve 'core-js/modules/es.array-buffer.constructor' in 'd:\me\svn\FE\src'
```

I know es.array-buffer is core-js3 feature, but I have no clue to find out which package wants it.

In summary, Could you give me some hint on how to track this error?

**Comment by patricklafrance** [comment]
Hi @silencej 

I dont think this has something to do with CRACO.

You should look for answers in the [CRA](https://github.com/facebook/create-react-app) or [Babel](https://github.com/babel/babel) repository.

I am closing this issue, if you think it's really an issue with CRACO, you can re-open it.

Patrick
